#!/usr/bin/env bash
# scripts/fidelity-deps.sh — the fidelity-gate local-runnability doctor.
#
# The hard fidelity gate (`corpus/generated/diff.sh`) only runs when a
# specific set of external tools + generated assets are present. On a
# fresh clone (and in lean/package-boundary CI) some are absent: the
# generated IDML/PDF pairs are gitignored or live in the private corpus
# repo, `corpus/samples/diff.sh` is the per-fixture render delegate, and
# `pdftoppm` (poppler) rasterises the reference PDFs.
#
# This script probes each dependency and reports it. It is purely a
# reporter:
#   exit 0  → every dependency present; the gate can run.
#   exit 1  → at least one dependency missing; the gate must SKIP.
#
# `make fidelity` consumes the exit code to decide PASS/FAIL/SKIP, and
# `make fidelity-deps` runs it standalone so a developer can see exactly
# what to install/fetch to make the gate runnable locally.

set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT" || { echo "cannot cd to repo root $ROOT" >&2; exit 2; }

MISSING=0
note() { printf '  %-4s %s\n' "$1" "$2"; }

echo "fidelity-gate dependency doctor (root: $ROOT)"
echo

# --- external tools -------------------------------------------------------
if command -v pdftoppm >/dev/null 2>&1; then
  note "OK" "pdftoppm (poppler) on PATH — $(command -v pdftoppm)"
else
  note "MISS" "pdftoppm not found — install poppler (brew install poppler / apt-get install poppler-utils)"
  MISSING=1
fi

if command -v python3 >/dev/null 2>&1; then
  note "OK" "python3 on PATH — $(command -v python3)"
else
  note "MISS" "python3 not found — diff.sh reads thresholds + drives paged-diff via python3"
  MISSING=1
fi

# --- gate driver scripts --------------------------------------------------
if [ -x corpus/generated/diff.sh ]; then
  note "OK" "corpus/generated/diff.sh present + executable"
else
  note "MISS" "corpus/generated/diff.sh absent/non-executable — the gate entrypoint"
  MISSING=1
fi

# diff.sh delegates per-fixture rendering to corpus/samples/diff.sh.
if [ -x corpus/samples/diff.sh ]; then
  note "OK" "corpus/samples/diff.sh present + executable (per-fixture render delegate)"
else
  note "MISS" "corpus/samples/diff.sh absent — diff.sh delegates per-fixture rendering to it (exits 2 without it)"
  MISSING=1
fi

# --- thresholds + paired fixtures ----------------------------------------
if [ -f corpus/generated/fidelity-thresholds.json ]; then
  note "OK" "corpus/generated/fidelity-thresholds.json present"
else
  note "MISS" "corpus/generated/fidelity-thresholds.json absent — defines the gated fixtures + tolerances"
  MISSING=1
fi

# Each gated fixture needs a paired InDesign-exported reference PDF. The
# IDMLs are regenerated by paged-gen (gitignored); the PDFs are the baked
# references and must be on disk. Count the pairs we can actually gate.
shopt -s nullglob
pdfs=(corpus/generated/*.pdf)
if [ "${#pdfs[@]}" -gt 0 ]; then
  note "OK" "${#pdfs[@]} reference PDF(s) under corpus/generated/ (e.g. $(basename "${pdfs[0]}"))"
else
  note "MISS" "no reference PDFs under corpus/generated/ — fetch the private corpus repo (LFS) or export them"
  MISSING=1
fi

echo
if [ "$MISSING" -eq 0 ]; then
  echo "RESULT: all fidelity-gate deps present — \`make fidelity\` will RUN the gate."
  exit 0
else
  echo "RESULT: fidelity-gate deps incomplete — \`make fidelity\` will SKIP (see MISS lines above)."
  exit 1
fi
